### ISSUE TITLE
nach dem Update auf 2021.02.3 keine Anmeldung im Browser möglich!

### ISSUE THREAD

**Issue by odesee** [tine20/tine20#7314]
nach dem Update auf 2021.02.3 keine Anmeldung im Browser möglich! - was tun?
Outlook und mobile Geräte scheinen zu funktionieren. Das Update lief auch ganz normal durch, ohne Fehlermeldungen!

Bitte um Unterstützung 

![grafik](https://user-images.githubusercontent.com/87531622/125952716-7e52dc0c-5706-4a62-9722-5f6e5e0f64c6.png)

**Comment by pschuele** [comment]
sieht man denn was in den logs (tine20.log, browser-js-console)?

**Comment by TheTheo53** [comment]
vieleicht hilft das. apache log file:

[Tue Jul 20 17:06:45.694348 2021] [php7:error] [pid 2169] [client 192.168.0.2:33634] PHP Fatal error:  Uncaught Error: Class 'Tinebase_Model_CommunityIdentNr' not found in /usr/share/tine20/Tinebase/Server/Abstract.php:172\nStack trace:\n#0 /usr/share/tine20/Tinebase/Server/Json.php(351): Tinebase_Server_Abstract::_getModelConfigMethods('Tinebase_Server...')\n#1 /usr/share/tine20/Tinebase/Server/Json.php(452): Tinebase_Server_Json::_getServer()\n#2 /usr/share/tine20/Tinebase/Server/Json.php(415): Tinebase_Server_Json->_handleException(Object(Zend_Json_Server_Request), Object(Error))\n#3 /usr/share/tine20/Tinebase/Server/Json.php(169): Tinebase_Server_Json->_handle(Object(Zend_Json_Server_Request))\n#4 /usr/share/tine20/Tinebase/Core.php(267): Tinebase_Server_Json->handle(Object(Tinebase_Http_Request))\n#5 /usr/share/tine20/index.php(24): Tinebase_Core::dispatchRequest()\n#6 {main}\n  thrown in /usr/share/tine20/Tinebase/Server/Abstract.php on line 172, referer: http://mein_server/tine20/

**Comment by ignoreigor** [comment]
Sieht nach 'nem Error aus. Wenn der beim Anzeigen der Index-Seite kommt, dann kann das schon die Ursache sein.
Datei /usr/share/tine20/Tinebase/Model/CommunityIdentNr.php da und lesbar?

**Comment by odesee** [comment]
Hallo Zusammen,

vielen Dank erstmal für die zahlreiche Infos.
Leider kann ich meine Logs erst am Sonntag wieder posten. habe aktuell wieder die funktionierende Version drauf gepackt.

**Comment by pschuele** [comment]
hm, seltsam, fehlt die datei im paket? ansonsten könnt ihr als hotfix einfach die datei aus dem git auf dem server ablegen. das müsste die richtige version sein: https://github.com/tine20/tine20/blob/af768cc524cb21e204efa509c5224d1bf1a07953/tine20/Tinebase/Model/CommunityIdentNr.php

**Comment by odesee** [comment]
habe aktuell nur im Downloadverzeichnis geprüft, ob die Datei da wäre - ist im Verzeichnis drin

**Comment by ignoreigor** [comment]
Eine open_basedir-Einschränkung hätte vermutlich auch die alte Version in der Konstellation nicht arbeiten lassen.
SELinux im Einsatz?

**Comment by TheTheo53** [comment]
> Sieht nach 'nem Error aus. Wenn der beim Anzeigen der Index-Seite kommt, dann kann das schon die Ursache sein.
> Datei /usr/share/tine20/Tinebase/Model/CommunityIdentNr.php da und lesbar?

Datei ist da und lesbar

**Comment by odesee** [comment]
> Im Download-Verzeichnis?
> Eine open_basedir-Einschränkung hätte vermutlich auch die alte Version in der Konstellation nicht arbeiten lassen.
> SELinux im Einsatz?

Ja, hatte auf dem Raspi wieder die funktionstüchtige Version eingespielt.
Das läuft auf dem Raspi 4 mit 8Gb Ram mit nem Raspbian. bis Version 2021.02.1 lief alles reibungslos

**Comment by TheTheo53** [comment]
> hm, seltsam, fehlt die datei im paket? ansonsten könnt ihr als hotfix einfach die datei aus dem git auf dem server ablegen. das müsste die richtige version sein: https://github.com/tine20/tine20/blob/af768cc524cb21e204efa509c5224d1bf1a07953/tine20/Tinebase/Model/CommunityIdentNr.php

Die Datei heruntergeladen und eingesetzt. Sie unterscheiden sich erheblich in der Größe.
Brachte aber leider keine Abhilfe.
CommunityIdentNr.php                                      │  10651
CommunityIdentNr.php_nachgeladen                          │ 214988


Immer wieder:
`Der Server kann Ihre Anfrage leider Aufgrund einer temporären Überlastung, 
Wartungsarbeiten oder Fehlkonfiguration nicht beantworten. Bitte 
versuchen Sie es später noch einmal oder kontaktieren Sie Ihren 
Administrator.`

**Comment by ignoreigor** [comment]
> Datei ist da und lesbar

Hoffe auch für den Webserver... Hmm, Raspbian, dann wahrscheinlich kein SELinux.

Kommt der Error wirklich beim Anmelden? Oder tauchte der halt mal auf... Evtl. auch mal das Tine-Debugging aktivieren, wobei die Error-Meldung, wenn sie da kommt, eigentlich schon aussagekräftig genug ist.

Irgendwie die Caches mal leeren? Oder nach Update Webserver mal durchblasen? Wüsste zwar nicht, wieso nun die Klasse da sein sollte, aber man weiß ja nie.

**Comment by ignoreigor** [comment]
Tinebase/Record/NewAbstract.php ist auch da?

**Comment by TheTheo53** [comment]
> > Datei ist da und lesbar 
> Hoffe auch für den Webserver... Hmm, Raspbian, dann wahrscheinlich kein SELinux.
 
Für alle
Nix Raspian : Debian 10.10

> Kommt der Error wirklich beim Anmelden? 
Ja

> Irgendwie die Caches mal leeren? Oder nach Update Webserver mal durchblasen? 

Immer: systemctl restart apache2
nach updates

**Comment by TheTheo53** [comment]
Falls du mich meinst:
> Tinebase/Record/NewAbstract.php ist auch da?
ja

> Und ./vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
Das kenne ich nicht in debian

> Was genau installiert Du denn? 
apt update
apt upgrade

**Comment by ignoreigor** [comment]
Ja, @TheTheo53 bei Dir scheint es ja auch nicht zu gehen. Mich interessierte mehr die Rasbian-Lösung von @odesee... zu späte gesehen, dass Ihr nicht die gleichen seid.
Und welches Repository hast du, @TheTheo53, für Dein Debian (oder welches Debian-Version nutzt Du) eingetragen?

**Comment by odesee** [comment]
> Tinebase/Record/NewAbstract.php ist auch da?
> Und ./vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php
> 
> Was genau installiert Du denn? Die Sourcen und du kopierst sie nach /usr/share oder ein Paket aus irgendeinem Repo?

Ja, die Datei ist auch vorhanden

**Comment by odesee** [comment]
> > > Datei ist da und lesbar
> > > Hoffe auch für den Webserver... Hmm, Raspbian, dann wahrscheinlich kein SELinux.
> 
> Für alle
> Nix Raspian : Debian 10.10
> 
> > Kommt der Error wirklich beim Anmelden?
> > Ja
> 
> > Irgendwie die Caches mal leeren? Oder nach Update Webserver mal durchblasen?
> 
> Immer: systemctl restart apache2
> nach updates

Raspbian ist auch nix anderes wie debian, in meinem Fall Buster

**Comment by TheTheo53** [comment]
> 
> Und welches Repository hast du, @TheTheo53, für Dein Debian (oder welches Debian-Version nutzt Du) eingetragen?

Debian 10.10

Hier läuft apt-cacher-ng daher:
deb http://127.0.0.1:3142/packages.tine20.org/debian buster stable

**Comment by odesee** [comment]
> Tinebase/Record/



> Ja, @TheTheo53 bei Dir scheint es ja auch nicht zu gehen. Mich interessierte mehr die Rasbian-Lösung von @odesee... zu späte gesehen, dass Ihr nicht die gleichen seid.
> Und welches Repository hast du, @TheTheo53, für Dein Debian (oder welches Debian-Version nutzt Du) eingetragen?

was würde denn dich genau interessieren?
Raspberry PI4 (8GB RAM), 1 TB SSD am USB3 die Die Konfiguration läuft über einen Reverse Proxy mit externen DB, die auf einem separaten Raspi4, natürlich wieder mit 8 GB RAM ausgestattet ist. Alles lief bis Version 2021.02.1 richtig schnell und ohne Probleme

**Comment by ignoreigor** [comment]
@odesee. Ah, na klar, gibt ja auch andere Images, als Raspberry Pi OS, das Debian-basiert ist. Habe mich schon gefragt, welche Repos Du da ziehst (oder ob Du mit den .deb-Files direkt agierst), bei den PHP-files mag es egal sein, bei der Verzeichnisstruktur wird es auch noch passen, aber bei den Paketabhängigkeiten wird es dann spannend. Wenn ich das richtig überflogen habe, gibt es die aktuelle Version ja nur für Buster (und natürlich andere Distros) 

Habe jetzt auch mal eine Paket-Installation mit Buster gemacht, allerdings im Docker-Container und nicht auf ARM, möchte mir ja das Ubuntu nicht versauen (ist ja auch nur ein Debian ;-). War Frickelei, aber läuft im Ergebnis sauber, allerdings auch wieder ohne ein Update von einer alten Version. An den Klassendateien oder den Abhängigkeiten habe ich bei allem Gefrickel nichts geändert.

Sind bei Eurem Update alle Pakete auf die aktuelle Version gezogen worden? 2021.02.3-1.100, vorallem tine20_tinebase und tine20_libraries? Die Fehlermeldung kommt, wenn die Anmeldemaske nicht geladen wird?

**Comment by TheTheo53** [comment]
So, aus dem backup vpm 16.7 zurück kopiert:
/usr/share/tine20
/var/lib/cache/tine20
/etc/apache2

Jetzt kann ich wenigstens wieder arbeiten. Die update Meldung ignoriere ich.
Tine Version ist 2021.02.2

Os: Debian 10.10

**Comment by odesee** [comment]
Hallo Zusammen,

anbei die versprochene Logs:

![image](https://user-images.githubusercontent.com/87531622/126898260-fbd3a0bb-42b3-401d-89f8-2aa354d12aaf.png)

**Comment by TheTheo53** [comment]
Nächster Schritt:
tine20-allinone_2021.02.3.zip runter geladen, ausgepackt in ein neues Verzeichnis. Altes und neues Verzeichnis entsprechend
umbenannt.
Und es läuft.

**Comment by odesee** [comment]
auch ich folgte heute dem Vorschlag von TheTheo53, war allerdings erfolgslos :( 
Bekomme jetzt diese Maske: 
![image](https://user-images.githubusercontent.com/87531622/128621671-bb3ff286-6a86-4946-968c-a2490ca4cb3d.png)

**Comment by katgirl** [comment]
Hatte heute das Problem nach dem Update auch via Ansible-Playbook

```yaml
#
# ansible-playbook -i others update_crm.yml --extra-vars="version=2021.02.1"
#
---
- hosts: crm
  tasks:
  - name: Download Package
    get_url:
      url: "https://packages.tine20.org/source/{{ version }}/tine20-allinone_{{ version }}.zip"
      dest: "{{ websitePath }}/tine20-allinone_{{ version }}.zip"

  - name: Unarchive the file that was download
    ansible.builtin.unarchive:
      src: "{{ websitePath }}/tine20-allinone_{{ version }}.zip"
      dest: "{{ websitePath }}"
      remote_src: yes

  - name: Unarchive the file that was download
    shell: "{{ php_path }} -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 setup.php --update"
    args:
      chdir: "{{ websitePath }}"

  - name: create files dir
    file:
      path: "{{ websitePath }}/files/"
      state: directory

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: "{{ websitePath }}/tine20-allinone_{{ version }}.zip"
      state: absent

```

Nachdem ich wie oben bereits beschrieben die Installation gelöscht 
```bash
rm -fR Verzeichnis
```
 habe und das Playbook habe noch mal laufen lassen + Copy Config-File lief es bei mir wieder.

**Comment by TheTheo53** [comment]
odesse:
> auch ich folgte heute dem Vorschlag von TheTheo53, war allerdings erfolgslos :(
> Bekomme jetzt diese Maske:

Hast du die Version 2021.02.2 wieder ans Laufen bekommen?
Erst danach habe ich  2021.02.3 ausgepackt und die Verzeichnisse umbenannt.

So, aus dem backup vpm 16.7 zurück kopiert:
/usr/share/tine20
/var/lib/cache/tine20
/etc/apache2
Erst danach habe ich  2021.02.3 ausgepackt und die Verzeichnisse umbenannt.

**Comment by odesee** [comment]
Habe eben getestet, leider auch hier (mit 2021.02.2) ohne Erfolg :(
![image](https://user-images.githubusercontent.com/87531622/129311464-e5b4e367-c73c-4296-82d7-2dc12f78bc08.png)

**Comment by katgirl** [comment]
> Hast du die Version 2021.02.2 wieder ans Laufen bekommen?

Ich bin von 2021.02.1 nach 2021.02.3 gegangen ohne Zwischenschritt -> Fehlermeldung
Danach bin ich auf  2021.02.2  weiterhin Fehlermeldung.

Dann habe ich das Installationsverzeichnis gelöscht und anschließend neu aus dem ZIP-File erstellt. Dann noch die Config kopiert, danach lief es bei mir (hatte vorher aber im Browser alle Cookies und Sessions gelöscht).

Falls du dich mit Ansible auskennst hier meine Konfig aus dem Ordner ```others``` 

```yaml
## -----------------------------------------------------------------------------
## All-Inkl
##
## user: 
## pass: 
##
## ssh-user: 
## ssh-pass: 
## -----------------------------------------------------------------------------
crm:
  children:
    crm:
      hosts:
        crm.DOMAIN.de:
      vars:
        ansible_user: USER
        ansible_python_interpreter: /usr/bin/env python3

        php_path: /usr/bin/php74
        websitePath: /www/htdocs/USER/crm.DOMAIN.de

```
Damit ließ sich das dann ganz einfach rauf und runter kopieren. Nur der Ordner ```/www/htdocs/USER/crm.DOMAIN.de``` auf dem Server muss existieren.
